# Generated by Django 4.2.26 on 2025-11-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
