# Generated by Django 4.2.26 on 2025-11-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_record_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
