# Generated by Django 4.2.26 on 2025-11-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
